export const LINE_DATA_FETCHED = 'LINE_DATA_FETCHED';
export const AREA_DATA_FETCHED = 'AREA_DATA_FETCHED';
export const BAR_DATA_FETCHED = 'BAR_DATA_FETCHED';
export const TABLE_DATA_FETCHED = 'TABLE_DATA_FETCHED';
export const PIE_DATA_FETCHED = 'PIE_DATA_FETCHED';
export const DOUGHNUT_DATA_FETCHED = 'DOUGHNUT_DATA_FETCHED';
export const INFO_DATA_FETCHED = 'INFO_DATA_FETCHED';
export const SIDEBAR_DATA_FETCHED = 'SIDEBAR_DATA_FETCHED';